-- Catch-up migration: the hiring tables below were applied straight to the database
-- on 2026-09-03 without a migration file, so a fresh clone of this repo could not
-- reproduce them. Everything here is written IF NOT EXISTS / idempotent, so running it
-- against the existing database is a no-op and running it against an empty one builds
-- the same shape.
--
-- Nothing in this file drops or rewrites data.

-- ── reference: where a candidate came from ────────────────────────────────────
create table if not exists hr.sources (
  name text primary key,
  sort integer not null default 100
);

-- ── reference: which recruiter owns the candidate ─────────────────────────────
-- "entity" in the Interview Tracker means the RECRUITER, not a company.
create table if not exists hr.entities (
  name           text primary key,
  default_source text,
  active         boolean not null default true,
  sort           integer not null default 100
);

-- ── reference: the columns of the Monthly Update grid ─────────────────────────
create table if not exists hr.tracker_stages (
  seq       integer primary key,
  label     text not null unique,
  counts_as text
);

-- ── one row of the monthly report: a position being hunted in a given month ───
-- Created from a ManPower requisition. carried_from_row_id points back at the
-- previous month's row when an unfinished position rolls forward.
create table if not exists hr.tracker_rows (
  id                  bigint primary key generated by default as identity,
  month               date   not null,
  manpower_request_id bigint not null references hr.manpower_requests(id) on delete cascade,
  position            text   not null,
  carried_from_row_id bigint references hr.tracker_rows(id),
  created_at          timestamptz not null default now()
);

-- ── a person in the pipeline, hanging off one tracker row ─────────────────────
create table if not exists hr.candidates (
  id                  bigint primary key generated by default as identity,
  tracker_row_id      bigint references hr.tracker_rows(id)      on delete set null,
  manpower_request_id bigint references hr.manpower_requests(id) on delete set null,
  name                text,
  email               text,
  phone               text,
  position            text,
  source              text,
  entity              text,
  stage               text not null default 'Test Sent',
  outcome             text,
  resume_id           bigint references hr.resumes(id)           on delete set null,
  tracker_id          bigint references hr.interview_tracker(id) on delete set null,
  source_filename     text,
  applied_at          timestamptz,
  created_by          text,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create index if not exists candidates_tracker_row_idx on hr.candidates (tracker_row_id);
create index if not exists candidates_stage_idx       on hr.candidates (stage);
create index if not exists tracker_rows_month_idx     on hr.tracker_rows (month);

-- ── RLS ───────────────────────────────────────────────────────────────────────
-- Every table in this project has RLS on; a table with no policy returns zero rows
-- and reports no error, which is the single easiest way to lose a day debugging.
alter table hr.sources        enable row level security;
alter table hr.entities       enable row level security;
alter table hr.tracker_stages enable row level security;
alter table hr.tracker_rows   enable row level security;
alter table hr.candidates     enable row level security;

-- Postgres has no CREATE POLICY IF NOT EXISTS, so each is dropped first. These
-- match what is already live, so re-running changes nothing.
drop policy if exists src_read on hr.sources;
create policy src_read on hr.sources for select using (true);

drop policy if exists ent_read  on hr.entities;
create policy ent_read  on hr.entities for select using (true);
drop policy if exists ent_write on hr.entities;
create policy ent_write on hr.entities for all
  using (app.can_write('hr')) with check (app.can_write('hr'));

drop policy if exists ts_read on hr.tracker_stages;
create policy ts_read on hr.tracker_stages for select using (true);

drop policy if exists tr_all on hr.tracker_rows;
create policy tr_all on hr.tracker_rows for all
  using (app.can_read('hr')) with check (app.can_write('hr'));

drop policy if exists cand_all on hr.candidates;
create policy cand_all on hr.candidates for all
  using (app.can_read('hr')) with check (app.can_write('hr'));

grant usage on schema hr to authenticated;
grant select, insert, update, delete
  on hr.sources, hr.entities, hr.tracker_stages, hr.tracker_rows, hr.candidates
  to authenticated;

-- ── seed reference data ───────────────────────────────────────────────────────
-- The three recruiters, each with the job board they normally source from. The
-- default only pre-selects the dropdown; it is always overridable per candidate.
insert into hr.entities (name, default_source, sort) values
  ('Khushbu Singh',  'Indeed',   10),
  ('Suchandra Das',  'LinkedIn', 20),
  ('Uzma Ahmed',     'LinkedIn', 30)
on conflict (name) do nothing;

insert into hr.sources (name, sort) values
  ('LinkedIn', 10), ('Naukri', 20), ('Indeed', 30), ('Reference', 40)
on conflict (name) do nothing;
