-- A record of every meaningful moment in the causelist action-review popup's life for a case:
-- exported (claimed for someone to review), answered (needed or not, with due date/person if
-- needed), or closed via the X without answering. mis_cases only ever remembers the LATEST
-- state (reviewed_at/action_needed/reviewed_by/pending_by) - this is what lets the new "Causelist
-- Reviews" tab show a real history instead of just today's snapshot, and answers "who's been
-- sitting on this" / "how many times did this get closed before someone actually answered it".
create table if not exists public.mis_causelist_review_log (
  id bigint generated by default as identity primary key,
  case_id bigint not null references public.mis_cases(id) on delete cascade,
  event text not null check (event in ('exported','answered','closed_without_answering')),
  actor text,
  detail jsonb,
  created_at timestamptz not null default now()
);
create index if not exists mis_causelist_review_log_case_id_idx on public.mis_causelist_review_log(case_id);
create index if not exists mis_causelist_review_log_actor_idx on public.mis_causelist_review_log(actor);
create index if not exists mis_causelist_review_log_created_at_idx on public.mis_causelist_review_log(created_at);

comment on table public.mis_causelist_review_log is
  'Event log for the Legal MIS causelist action-review popup (nexus-core.js clrevMaybeOpen/clrevSubmit/clrevClose). One row per exported/answered/closed_without_answering moment, per case.';
comment on column public.mis_causelist_review_log.detail is
  'For event=answered: {needed: boolean, due: date-string|null, person: email|null}. Null for exported/closed_without_answering.';

-- Every other mis_* table in this schema is wide open (qual/with_check true) - matches that.
alter table public.mis_causelist_review_log enable row level security;
create policy mis_causelist_review_log_all on public.mis_causelist_review_log for all using (true) with check (true);
